import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import CartContextModule from "@/Context/CartContextModule";

const inter = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "mosh demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextModule>
          {children}
        </CartContextModule>
      </body>
    </html>
  );
}
